Fix a cross-device mv error by using a tmp directory inside document root (#886)
Solves the [error discovered by
@sejas](https://github.com/WordPress/playground-tools/pull/116#issuecomment-1747287593)
caused by calling `php.mv(fromPath, toPath)` when `fromPath` is a
mounted local directory and `toPath` is a MEMFS directory. Emscripten
doesn't support such a scenario:

```
Proceeding without the Notification plugin. Could not install it in wp-admin. The original error was: Error: Could not move "/tmp/assets/Notification/notification": Cross-device link.
Error: Could not move "/tmp/assets/Notification/notification": Cross-device link.
    at descriptor.value (/playground-tools/node_modules/@php-wasm/node/index.cjs:67481:17)
```

The solution proposed in this PR replaces a `/tmp` directory with a
randomly-named temporary directory inside `wp-content`. `/tmp` doesn't
necessarily point to a system temp directory and needs to be revisited
anyway. Whether we should use a temporary directory inside `wp-content`
is another matter, but that part may be revisited once the [recursive
cp](https://github.com/WordPress/wordpress-playground/pull/846) feature
is added.