Explore compiling PHP to WASI for node.js-less CLI compatibility
This commit explores using the wasmenv toolkit to compile PHP.
The configure phase works, but the make fails because setjmp is
unsupported yet, see the error message below and the relevant
GitHub issue at https://github.com/WebAssembly/WASI/issues/490

There's a chance "make" would work if we tried a dedicated libc build:

   https://github.com/WebAssembly/wasi-libc/blob/main/libc-top-half/musl/include/setjmp.h

I'm not sure if the final PHP build would be functional, though.

Either way, building using wasi-sdk which has libc and set_jmp.h baked
in would be a sensible next step:

https://github.com/WebAssembly/wasi-sdk/releases

31 69.49 /root/php-src/main/setjmp.h:44:2: warning: setjmp is not yet implemented for WASI [-W#warnings]
31 69.49 #warning setjmp is not yet implemented for WASI
31 69.49  ^
31 69.56 In file included from /root/php-src/ext/bcmath/libbcmath/src/div.c:32:
31 69.56 In file included from /root/php-src/ext/bcmath/libbcmath/src/config.h:7:
31 69.56 In file included from /root/php-src/main/php.h:35:
31 69.56 In file included from /root/php-src/Zend/zend_API.h:25:
31 69.56 In file included from /root/php-src/Zend/zend_modules.h:24:
31 69.56 In file included from /root/php-src/Zend/zend_compile.h:724:
31 69.56 /root/php-src/Zend/zend_globals.h:151:2: error: unknown type name 'jmp_buf'
31 69.56         JMP_BUF *bailout;
31 69.56         ^
31 69.56 /root/php-src/Zend/zend_portability.h:361:18: note: expanded from macro 'JMP_BUF'
31 69.56 # define JMP_BUF jmp_buf