Docs: better paths for links  (#1765)
## Motivation for the change, related issues

This PR removes "wordpress-playground" from links as it's not needed,
and to keep consistency with the rest of the links.

It also unifies links, removing relative paths so they start from root.

This change reduces the chance of errors when using these files for
other languages (See
https://github.com/WordPress/wordpress-playground/pull/1766)

This PR also fixes this error when doing `npm run build:docs`
```
Error: Docs markdown link couldn't be resolved: (../developers/23-architecture/18-host-your-own-playground.md) in "/Users/juanmanuelgarrido/PROJECTS/2024/wordpress-playground/packages/docs/site/docs/_fragments/_playground_wp_net_may_stop_working.md" for version current
    at Array.forEach (<anonymous>)
[ERROR] Client bundle compiled with errors therefore further build is impossible.
Warning: run-commands command "docusaurus build --out-dir ../../../dist/docs/build" exited with non-zero status code
```