CI: Fix intermittent docs build failures (#1307)
Building the documentation page often fails. This PR is an exploration
to fix it. It:

* Patches the typedoc library in `node_modules` as otherwise it won't
work with TypeScript 5.4 🙈
* Removes non-essential TypeDoc plugins (link API reference to MDN,
cross-link Typedoc modules)
* Copies the `rollup.d.ts` files to `dist` instead of moving them.
TypeDoc, apparently, expects to find them in their original location:

```
error TS6053: File '/home/runner/work/wordpress-playground/wordpress-playground/packages/php-wasm/web/src/rollup.d.ts' not found.
  The file is in the program because:
    Root file specified for compilation
```

## Testing Instructions

Restart the CI 5 times, confirm the build worked every single time.