Avoid errors due to log message formatting (#1726)
## Motivation for the change, related issues

Today, we attempt to reassign an error's message property for formatting
purposes, but this throws an exception if the error property isn't
writable or doesn't have a setter. For example:

```
TypeError: Cannot set property message of #<ErrorEvent2> which has only a getter
```

These are the assignments that occasionally lead to the error:

https://github.com/WordPress/wordpress-playground/blob/trunk/packages/php-wasm/logger/src/lib/handlers/log-to-console.ts#L9-L11

Since the assignments are just for formatting, it should be OK if we
just tolerate the failed assignment using `Reflect.set()`.

Fixes #1514

## Implementation details

Use `Reflect.set()` to avoid exceptions when the assignment fails.

## Testing Instructions (or ideally a Blueprint)

- CI
- Tested manually by causing errors in the PHP runtime