Bump TypeScript to 5.4.5, Fix CI build errors (#1299)
Related to https://github.com/WordPress/wordpress-playground/pull/1287

TypeScript 5.4.5 (well, technically 5.2) gives us the
[Disposable](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html)
interface for cleaning up resources.

Also includes the changes from [CI: Fix intermittent docs build
failures](https://github.com/WordPress/wordpress-playground/pull/1307):

Building the documentation page often fails. This PR is an exploration
to fix it. It:

* Patches the typedoc library in `node_modules` as otherwise it won't
work with TypeScript 5.4 🙈
* Removes non-essential TypeDoc plugins (link API reference to MDN,
cross-link Typedoc modules)
* Copies the `rollup.d.ts` files to `dist` instead of moving them.
TypeDoc, apparently, expects to find them in their original location:

```
error TS6053: File '/home/runner/work/wordpress-playground/wordpress-playground/packages/php-wasm/web/src/rollup.d.ts' not found.
  The file is in the program because:
    Root file specified for compilation
```